### ISSUE TITLE
Barrels causing crash when interacting

### ISSUE THREAD

**Issue by Sixdd6** [asiekierka/CharsetMC#231] opened 2018-05-05 16:17 UTC
I've had two crashes so far, both on a server. The crashes both happened when a player right-clicked (inserted) into a barrel. The first crash was a hopping barrel into a normal barrel, rightclicking the hopping barrel. The second was a normal barrel alone.

[crash report](https://gist.github.com/Sixdd6/3d77071e2658559da783073a6606ed50)

Minecraft 1.12.2
Forge 2655
charset 0.5.0.244

If you need any other information just let me know.

**Comment by Sixdd6** [comment] 2018-05-05 16:18
Side note, both crashes happened within 15 minutes of a server restart, after the crash the server restarted and everything was fine till the next scheduled restart.

**Comment by asiekierka** [comment] 2018-05-06 10:35
Duplicate of #229

**Closed as completed by asiekierka** 2018-05-06 10:35 UTC
Labels: duplicate
