### ISSUE TITLE
Backpack crash report

### ISSUE THREAD

**Issue by TheChronomancer** [asiekierka/CharsetMC#45] opened 2016-01-26 01:12 UTC
[crash-2016-01-25_18.08.57-client.txt](https://github.com/asiekierka/CharsetMC/files/104274/crash-2016-01-25_18.08.57-client.txt)

**Comment by copygirl** [comment] 2016-01-26 04:04
> ```
> net.minecraftforge.fml.common.LoaderException:
> Caused by: java.lang.NoClassDefFoundError: pl/asie/charset/storage/backpack /TileBackpackRenderer
> Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.animation.FastTESR
> ```
> Charset version: 0.2.1
> Forge version: 11.15.0.1715

@TheChronomancer Try using latest Forge.

If the cause is what I think it is, these crashes could be fixed by requiring the proper forge version.
(Of course, you also have to remember to actually include / update that requirement as new Forge features are used.)

**Comment by asiekierka** [comment] 2016-01-26 07:32
Yeah. I forgot to set 0.2.1 to require 1718. Sorry!

2016-01-26 5:04 GMT+01:00 copygirl <notifications@github.com>:

**Closed** 2016-01-26 13:20 UTC
