### ISSUE TITLE
Rustic and Traverse Chest and Barrel

### ISSUE THREAD

**Issue by Fortist** [asiekierka/CharsetMC#259] opened 2018-07-22 20:34 UTC
Edit: It seems that it's the fault of "NoTreePunching" mod, which changes plank recipes.

While, the colored planks from rustic work, the regular Iron and Olive Logs and Planks do not work for barrels or chests respectively. Same for Traverse's Fir Wood.

**Comment by asiekierka** [comment] 2018-07-22 20:59
Yes. If such mods are present, only vanilla and a few other plank types will work, as I rely on recipe scanning to get my work done.

In the case of NoTreePunching, [this code](https://github.com/alcatrazEscapee/no-tree-punching/blob/master/src/main/java/notreepunching/recipe/ModRecipes.java#L275-L345) is the culprit. It would have to run after the FML post-initialization phase for it to be compatible with Charset.

I'm not sure if I'll introduce another way of gathering the necessary data eventually.

**Comment by asiekierka** [comment] 2018-07-26 08:16
Duplicate of #123.

**Closed as completed by asiekierka** 2018-07-26 08:16 UTC
Labels: duplicate
