### ISSUE TITLE
Charset Lib Crash

### ISSUE THREAD

**Issue by WenXin20** [asiekierka/CharsetMC#415] opened 2019-08-08 05:41 UTC
Minecraft v1.12.2
Forge v14.23.5.2838
Charset Lib v0.5.6.3
Charset Barrels v0.5.6.3
Charset Chests v0.5.6.0
Charset Immersion v0.5.6.0

I got this crash while loading the game, not sure what causes it though.
[Crash Report](https://paste.dimdev.org/oqahivujij.mccrash)

**Comment by noobanidus** [comment] 2019-08-08 08:48
Appears to be the same as #414 Do you have the latest NetherEx installed?

**Comment by WenXin20** [comment] 2019-08-08 14:33
Yes

**Comment by asiekierka** [comment] 2019-10-26 08:24
Duplicate of #414.

**Closed as completed by asiekierka** 2019-10-26 08:24 UTC
Labels: duplicate
