### ISSUE TITLE
Suggestion/Idea: Tanks retain fluid when broken

### ISSUE THREAD

**Issue by Ithronyar** [asiekierka/CharsetMC#200] opened 2018-02-28 01:14 UTC
Charset tanks should be breakable without destroying whatever is inside them. Ideally, fluid-filled tanks in the inventory would also have a tooltip indicating what fluid they're holding, and their contents would be rendered. Tanks with identical contents could stack in the inventory, reducing clutter.

**Comment by copygirl** [comment] 2018-02-28 03:02
Same could be said for chests.

I would rather you can pick up at max one tank using the carry functionality, therefore having to rely on setting up more interesting liquid transportation setups (using minecarts?) rather than trivializing it by simply transporting a large amount of containers in your inventory, especially when stackable.

There's already plenty of mods that do it exactly like you described, so you're not really missing out on anything if you can just use those.

**Comment by Ithronyar** [comment] 2018-02-28 03:28
> Same could be said for chests.

Break a chest and its contents fall out. Break a tank and it deletes its stored fluids from existence. Not even close to the same thing. Imagine if you could never break chests (not even accidentally), or else all your stored items got deleted.

>more interesting liquid transportation setups

Not practical when you need to transport them over long distances. Lay dozens/hundreds of minecart tracks for a one-time moving operation? Impractical. Pump all the fluid through pipes? Impractical. Want to transport fluids between dimensions? Too bad, you need another mod, or have to fudge around with launching minecarts through portals. Or you need to use some other hackish method instead of just carrying your tanks.

By that logic, we should only be able to carry one block at a time. They're whole cubic meter, after all: Even bigger than fluid tanks. All blocks would have to be moved in minecarts or item pipes or whatever. The game would quickly get extremely boring, since most of your time would just be spent setting up block transport systems. It's an extreme example, but that's basically the logic for only carrying one tank at a time. It's an inefficient and arbitrary limitation, and the mod would be quickly discarded for more efficient and less time-wasting alternatives.

There's a reason so many mods don't delete your fluids when a tank is broken: It's just good design. Calling arbitrary mass destruction of potentially valuable fluids a good design choice is laughable. There's no way of knowing that it's going to destroy your fluids when broken, and since most players are accustomed to having practical portable tanks, they would have to always remember "Oh yeah, the charset tanks will delete my fluids, so I can't pick them up" or risk losing their resources because they had the audacity to _move a fluid tank_. That's not immersive at all.

I'm fine with no stacking, though. It's more of a quality-of-life feature and makes sense since you can stack blocks, but it would make mass fluid transport too easy.

**Comment by gjgfuj** [comment] 2018-02-28 05:57
Better: make the fluid tanks explode liquid source blocks as much as they
are full when broken.

**Comment by asiekierka** [comment] 2018-02-28 06:04
Charset contains a block carrying feature which is meant to be used for carrying blocks as-is.

Also, in vanilla, if you break a fluid block (by, say, placing another block in its place), you irreversibly lose that fluid as well. For items, destruction is far more difficult and requires a more deliberate circumstance (such as dropping an item into lava).

Charset tanks are also not entirely lossy - they will, for instance, drop a single source block of fluid when blown up. I have considered @gjgfuj's solution here - that is, exploding the liquid source blocks - but I had somewhat justified concerns about, say, breaking a lava tank in a wooden house. It would definitely make a lot more sense than just carrying the contents, anyway.

There's multiple solutions to tackle this problem. BuildCraft for 1.11+ drops fluids into 500mB-sized "crystals", which can then be re-inserted into a fluid inventory - that way, losses are minimal. Another route would be to add a can item, as some older mods do, which allow you to stack fluids, take them out of the tank and carry them to another container. Yet another route is to simply match vanilla's behaviour for chests and explode the source blocks.

Mass destruction of the fluids is not a design choice here; it's a _lack_ of a design choice, we have not decided and we have not tackled this usecase very well yet (short of allowing carrying of tanks). 

(And yes, I am upset about shulker boxes.)

**Comment by asiekierka** [comment] 2018-02-28 06:07
Also, you mentioned most players being accustomed to a specific feature being present. Charset's Tanks are based off BuildCraft's, and so keep in many ways to their original design.

Players are also accustomed to having storage-upgradeable barrels (as in Storage Drawers, JABBA or YABBA); however, we don't do this. Players are accustomed to having single-block autocrafters; however, we don't do this. Charset has never really put "the standard" as a design principle other than perhaps as a way to compare things.

The mod is highly modular; as such, if someone wants portable tanks which keep their contents or store more than 16 buckets in a block, we encourage them to use one of the many mods which provide this functionality.

I am not opposed to solving the usecase of transporting large amounts of fluids; however, options have to be evaluated a bit more carefully.

**Comment by Ithronyar** [comment] 2018-02-28 07:51
@asiekierka Avoiding portable tanks seems like more trouble than it's worth. Adding a new "solid fluid" item just means portable fluids with unnecessary complication, possibly with a bunch of new item registries in the game. Not to mention the absurdity of breaking a fluid tank and its contents inexplicably dropping solid items (or even worse, liquid ones).

Exploding the liquid everywhere could cause massive destruction with some mods' liquids, and potentially cause lag and crashes. Imagine a block-destroying mod liquid that creates a chain reaction that destroys other tanks with the same liquid, resulting in a giant crater where the player's base used to be.

And if we're going to adhere to vanilla's logic as if it's somehow some golden standard for gameplay design: Fluids aren't items. They're not really even blocks. They don't need to explode out of a container just because items do.

Also, standards exist because they tend to be the optimal way to do things. Breaking from the standard is fine when it has better results, but I don't think anyone in their right mind would think fluid-destroying tanks or an overcomplicated conservation mechanic is better than just picking up the tanks with fluid inside them.

And if you _really_ don't want portable tanks and insist on an overcomplicated solution for the sake of being different, here's a new idea that solves this whole fluid conservation dilemma: Tanks that aren't actually tanks, but more like racks for a new fluid cell item. You make the "tank" as an empty casing, which can't hold any fluids on its own. You need to install fluid cells to "upgrade" the tank's storage capacity, with a limit of 16 cells per tank block. Then you can interact with it as usual. When the tank is broken, it drops the empty rack and the fluid cell items, which retain their stored fluids. Fluid is conserved, and everything works logically. It's a weird system and far less practical than portable standalone tanks, but it's the only way I can see this whole "drop everything when you break the tank" mechanic actually working well.

**Comment by asiekierka** [comment] 2018-02-28 09:05
Actually, exploding the liquid everywhere makes more sense than you think when you put it this way: this could add a new element of danger for storing dangerous liquids. I think it's a worthwhile gameplay element worth pursuing further - high-end technology is nowhere near as delicate as it ought to be! (As for lag and crashes, that's on those mods, not me. If they can't handle a few hundred of the fluid block being placed in-world, they'd break with some more vanillaesque usages anyway - I've seen people build multiblock tanks by simply pouring the actual liquid into a block space!)

Fluids aren't only blocks because Forge willed it so to allow mod intercompatibility. Mojang has blocks, buckets (which directly relate to blocks), bottles (which kinda-sorta do) and the Cauldron (which, again, kinda-sorta does). The primary means of liquid storage being blocks and buckets, where buckets map to blocks in a 1:1 manner. Therefore, I think considering fluids in the block/item area is perfectly reasonable.

I agree that the "solid fluid" idea doesn't hold up to scrutiny in this case, although BuildCraft also uses it for fluid pipes - where dropping a full fluid pipe simply makes no sense (fluid can also be stored on connections, which can disappear).

Standards exist because they tend to be the optimal way to do things, yes, but sometimes "optimal" simply means "simplest way which works with most mods" - see: Redstone Flux, which is effectively a lowest common denominator of the power systems that came before it.

Many people prefer a more challenging gameplay experience. The niche communities centered around mods such as GregTech, Reika's mods or TerraFirmaCraft prove it - and, as there is no shortage of tank mods implementing the "standard" ways, I'm very keen on experimenting.

Racks for fluid cell items is weird and impractical, yes. It's effectively portable tanks with an artifically lowered stacking limit (fluid cells contain 1 bucket per item, tanks contain 16 buckets per items - but you could just make tanks stack less, or add a weight mechanic to the player's inventory to discourage carrying 27 tanks).

Additionally, to consider chest movement vs. block carrying: The player has 36 slots of items, which is 4/3rd of one chest. If we extrapolate it to a tank with 16 buckets, that means the player should be able to hold at most 4/3 of a tank - 36 buckets plus the ability to carry a tank of 16 buckets (with the block carrying module active) gives 52 buckets, which is already far ahead. It's a bit silly, but I think - if we agree that storing 16 buckets in an easily accessible form in one block space is roughly "as balanced" as storing 27 stacks in an easily accessible form in one block space - it's worth at least keeping in mind.

**Comment by Ithronyar** [comment] 2018-02-28 10:15
The problem with "challenging" features is that too many developers make them artificially inefficient, unintuitive, and a waste of time and resources. Not very complex or hard to understand; just large effort for minimal gain. Unless you know the arbitrary design quirks of those features, they're going to eventually waste even the most cautious player's time and resources, because they abandon logic and practicality for "difficulty".

Making tanks explode liquid everywhere when you just want to move them sounds a lot like that. Tanks are simple. You put liquids in, you take liquids out. It's not super-advanced technology; it's just a container. Barely an upgrade from storing buckets in a chest.

But let's ignore their technological complexity (or lack thereof), and focus on gameplay and balance, since that's what matters most here.

By volume, chests are more efficient for fluid storage, since you can put 27 buckets in them, whereas you can only store 16 fluid blocks in a tank. Making tanks spawn liquid everywhere makes them almost useless due to sheer inconvenience. Store fluid buckets in a chest, and you can move the contents just fine. Store fluid buckets in a non-portable tank, and you get punished for using the tank. It has lower storage capacity, _and_ it spews its potentially dangerous contents everywhere if you want to move it, basically griefing the area. Let's face it: Cleaning that up isn't fun or interesting, just tedious. It's not user error or stupidity at fault, but due to deliberate mod design. It punishes players for mistakes they didn't make.

Make tanks portable, and they're suddenly worth using. They may have smaller storage capacity than a chest, but they can render their contents, connect into a multiblock, and be transported. Inventory volume shouldn't really be a concern, either: You can carry 64 cubic-meter blocks in one slot, but storing 16 blocks' worth of fluid in a tank suddenly isn't balanced? That's just ridiculous.

You may say "But you can only store one bucket per slot!" True, but it's also a primitive way of storing fluid, and more like a pipette. You fill it, you empty it. It's only a tool, not a specialized storage method. Fluid tanks _are_ a specialized storage method, and they should be more efficient as a result.

One more thing about balance: So what if players can transport 576 blocks of fluid in their inventory (in the form of filled portable tanks)? They can already hold 2,304 blocks in that same space, so the tanks aren't overpowered at all.

Regardless of balance, non-portable tanks still make long-range and interdimensional liquid transport annoying and impractical. Obviously, every player has a different tolerance for such things. But whenever possible, it tends to be a good idea to _not_ make the game a tedious grind just to accomplish one thing, such as moving a resource from point A to point B. If you need to move large amounts of fluid, non-portable tanks make a simple task an enormous waste of time and resources.

**Comment by asiekierka** [comment] 2018-02-28 10:33
Making tanks explode liquid everywhere isn't meant for mere moving. If you break a chest above lava when you wanted to move it, you will lose most of the items, or spew them across your base. I'm thinking more in terms of PvE: Imagine that a creeper blowing up in your lava energy factory would suddenly become a lot more dangerous, prompting the player to build additional defenses.

Perhaps there could be other ways of making the movement of tank content easier. One could make it so that buckets are filled automatically if sufficiently immersed in liquid, mimicing item pickup behaviour. One could make it so that right-clicking a tank with sixteen buckets fills all of them, like double right-clicking a barrel with an item will take all of the item's instances from your inventory right now.

The benefits of tanks are really in terms of machine accessibility. I'm already evaluating ways in making bucket<->tank conversion easier, the most likely idea seeming to be using the Charset-improved Cauldron with Dispensers as a conversion mechanism.

I still stand by that allowing portable tanks would also necessiate allowing portable barrels (the silky upgrade does exist, but only to keep compatibility - it will be removed in 1.13, most likely) and portable chests. Rather, I think it might be more worthwhile to make it easier to move contents in and out of a tank, just like there exist mods (Inventory Tweaks, Mouse Tweaks, Inventory Sorter) to make inventory manipulation easier and faster. This could provide sufficient aid for the most common usecase I see for moving tanks in Charset, which is moving bases (a task which should not be made too easy, as to promote setting up more advanced settlements).

In addition, I still stand by that Charset does not optimize for the Standardized Modding Environment as defined by common kitchen sink modpacks. Interdimensional and long-range transport is only planned to exist through the scope of minecarts in the aforemenited vision, although I do plan to make setting up minecarts easier in some manner (using a tape measure of some kind to automatically place a large amount of rails within a defined path?).

Again, I am aware of the problems you're naming, but I still feel that in the scope of mods which aren't far beyond Charset's definition of balance and thus not really worth catering to by said mod, the uses you bring up are either far less common than you name, or better solvable at the root of the problem (for instance, larger settlements could be encouraged by tweaking ore generation as to create large, difficult to harvest "mines" of ore as opposed to small randomized blobs; the difficulty of setting up cart networks could be reduced; the difficulty of manually removing and inserting the contents of a tank could be made easier).

**Comment by skyem123** [comment] 2018-02-28 10:34
I played a lot of Minecraft when the standard was that tanks lost water when you broke them. :p
The thing is the balance of ease of use to making players think is hard to find, I'm going to suggest experimenting and trying to see what is more fun. As asie said, this mod has its own differences, nothing is stopping you from using tanks from other mods. Something that I think is worth noting is that tanks have the advantage over chests, being that they're already dealing with fluids rather than items, so you don't have to keep on putting things into and out of buckets...

**Comment by asiekierka** [comment] 2018-02-28 10:48
In general, the flaws you point out are valid, but I feel you're trying to solve the symptom as you see it, whereas I'd rather try to analyze it more first and possibly try to fix the cause altogether.

Yes, I do get very defensive about seemingly trivial things - sometimes for the better, sometimes for the worse; it's always clearer in hindsight. We'll see.

**Comment by copygirl** [comment] 2018-02-28 11:32
I would also like to mention that your issue is already solved in the form of many other mods, @Ithronyar. Doing things such as trying to impose your ideals onto someone else's mod is the kind of thing that has many mod developers speak of modded Minecraft's userbase as "entitled". Modders aren't there to work for you for free. They have their own ideas and design goals. You're free to use another mod. You're free to make your own fork of charset with the change you're seeking for.

Of course you're free to bring up criticism and arguments to the table for consideration, and that's what @asiekierka did. I just want to add that making liquid non-trivial to move allows it to be more valuable than it is currently. (Also I wouldn't mind a full-conversion mod that does away with the ability of carrying more than one blocks.)

**Comment by asiekierka** [comment] 2018-02-28 12:23
@copygirl He was not hostile or offensive, I would not call him "entitled", merely curious and ready for debate - and that is fine! The line is drawn when it becomes an attack.

**Comment by Ithronyar** [comment] 2018-02-28 12:54
@copygirl I don't demand anything, insult anyone, or even expect anything to be done as a result of my actions. I'm trying to help a developer improve a mod (or even just provide some ideas) based on years of experience with UX and game design. I'm terse and a little sarcastic, but not entitled.

**Comment by asiekierka** [comment] 2018-02-28 12:59
You definitely gave me a context, although I was aware of the problems - I just do not wish to rush blindly into the status quo.

Charset will feel incomplete for quite a while, as the components linking ideas together do not all exist yet - such as the power systems, improved minecart stuff, new ore generation, etc. I am evaluating features in a context which is not fully existing yet, so I want to be a bit more careful. And, again, "popular mods X and Y won't work well without feature Z" only applies insofar as they fit the overall, bigger design principles already - I do not plan to cater to every modpack, as I want Charset to have a roughly concrete set of features - I would rather someone take the mod, fork it, rename it than add a config option or make a decision I am not entirely confident in.

**Comment by asiekierka** [comment] 2018-02-28 13:01
And thank you for your time and input, you have been very descriptive.

**Comment by Ithronyar** [comment] 2018-02-28 13:35
No problem, I hope it proves useful. :)

**Comment by copygirl** [comment] 2018-02-28 15:42
@Ithronyar I'll be honest, I got reminded by your approach of both a friend who's known to argue for the sake of winning rather than logic (meaning sometimes accepting admitting "defeat") and, as I already said, the "entitled Minecraft players". I didn't mean to say you act as such, just point out that it might appear so to some people. So I apologize that that's how it came across. I still have to learn a lot in regards to open discussions, too.

Specifically I want to point out the lengths to which you were willing to go to get across your points, as it might be distracting from the actual arguments. For the record, the points I was trying to make:

- Other mods already exist that do exactly what you're requesting. Why duplicate behavior?
- You can pick up a single tank at a time with the block carry feature of Charset.
- Trivializes liquid transport. In my last comment I mentioned how that devalues liquids.

I felt like the first point was completely ignored and the others barely touched on. You just mentioning your subjective opinion on how you prefer the game to be played and validating this with existing game mechanics. As asiekierka said, other preferred gameplay styles exists, and I'm certainly in the that boat - enjoying what many people would likely call grindy.

**Comment by asiekierka** [comment] 2018-02-28 15:53
* "Why duplicate behaviour?" is a bad question to ask. What i'm asking is "why blindly duplicate behaviour?" - the difference is just one word, but it's far from subtle. I just think options should be exhausted first, or experimented with until something pleasant is found. The only way in which the duplication aspect matters is in that it gives us *more* freedom to experiment - instead of having to add a stopgap measure, we can just recommend dissatisfied players to use another mod until we figure out what we enjoy personally.
* In regards to trivializing liquid transport - as I already estabilished, you can carry 4/3 of a chest using your inventory (or 7/3 of a chest, if you also utilize your Ender Chest - never liked it too much, though), or 9/4 of a tank using your inventory and buckets (or 63/16 of a tank if you also utilize your Ender Chest). I think the difficulty of transferring fluids is thus on par with the difficulty of transferring items. Other issues pointed out, such as the pointlessness/difficulty of setting up cart networks, are being evaluated but I'd rather fix them closer to the source.

**Comment by copygirl** [comment] 2018-02-28 16:22
> "Why duplicate behaviour?" is a bad question to ask. What i'm asking is "why blindly duplicate behaviour?" - the difference is just one word, but it's far from subtle.

If that's what you're asking, then my own answer would obviously be "don't", especially in this context. And I disagree that it's a bad question. There should be some benefit of being a copycat. It could be attempting to be a mod which offers most things modded players want without having to rely on other mods which have essentially the same feature. Which, I thought, wasn't what Charset was trying to achieve - and you mentioned the mod's modular nature. The other reason could be that the same-y things should still fit in the mod's theme or provide better integration with other features.

Generally, :+1: on improving existing ways of transport (or providing interesting alternatives) rather than solving everything the easy, "convenient" way by just having the player carry everything.

**Comment by asiekierka** [comment] 2018-02-28 16:37
No, I didn't mean that we should strive to duplicate behaviour; rather, I think it's fair to integrate ideas which are sensible into the mod, even if such ideas already exist in some context. Thus, the fact that they already exist out there, somewhere, should not be a limiting factor in our decisionmaking - of course, there's no point in having two identical-yet-"competing" solutions (after all, I did remove my own backpacks when yours came along). There's a difference between "allowing oneself to use sensible ideas" and "striving to use existing ideas instead of pushing oneself to see if different approaches exist".

**Comment by Ithronyar** [comment] 2018-02-28 17:19
@copygirl The core of my entire argument is resource conservation and logic. To a lesser degree (due to subjective player preference), practicality and a balance of investment VS reward. Nothing I propose is ever about blindly duplicating features or forcing my own opinion like some feature fascist, but pointing out solutions for a problem. It's easy for an idea to look copied when it's the most practical solution.

Objective problem: Right now, tanks destroy stored fluids. This needs to be fixed. It's a massive violation of resource conservation, and unfairly destroys a lot of resources. Possible solutions:
**1.** Make tanks explode their fluids everywhere when broken.
**2.** Make them drop weird surrogate fluid storage items.
**3.** Replace tanks with a weird and impractical pseudo-tank that's actually a container for a bunch of modular fluid storage items, which drop when the tank is broken.
**4.** The tank drops with its stored fluids intact.

1 and 2 only introduce more problems.
1 could easily kill players and grief/destroy large amounts of resources and entire bases, especially with more dangerous modded fluids. This might be fine if only player error could ever be the sole cause, but that's not likely. Someone at some point will try to mine a tank to move it, because it's the logical thing to do with every other block in the game. Punishing the player for thinking logically is a cardinal sin of gameplay design.
2 doesn't make sense.
3 is overcomplicated and just a portable tank with extra steps. Unique, but not better.
4 is clean and simple, and doesn't troll you with destroyed resources or a griefed base. Inventory transport balance is easy to tweak if that's still an issue: A more expensive crafting recipe, and/or less fluid storage per tank. I've already pointed out how the player's fluid carrying capacity with full tanks would be nothing compared to block carrying capacity, so I won't reiterate that.

And I'm going to point out what I hope is obvious: Not everyone wants to have to build some sort of pipe/rail system to transport fluids from one place to another, or babysit a minecart full of buckets (or a tank), or walk back and forth doing nothing but manually carrying and emptying buckets. That's not mentally stimulating. You're not solving problems or being challenged. It's just a tedious, grindy, menial task that you need to do as a means to an end in a larger plan.
I'll also acknowledge that some players are masochistic. They like an hours-long grind for the tiniest of progress, and they want to spend days/weeks/months on what should be a trivial minutes-long project. They want the game to be more difficult and impractical than real life.

This is ultimately about polar opposite solutions to the same problem: Players are either forced into roundabout and time-consuming fluid transport solutions, or they can just simply use tanks themselves to move fluids around. I see no compromise that doesn't ruin both goals.
So, here's a more universal solution, @asiekierka : A config option for tank drop behavior. Just implement both the explode-fluids-everywhere and the retain-fluids-on-drop solution. And a config for tank storage capacity, if it's not already a thing (I didn't see one). This solves the resource conservation problem, and everyone can balance and configure their tanks as desired. How users want to use the mod's tanks should be up to them, anyway.

**Comment by asiekierka** [comment] 2018-02-28 17:39
>Objective problem: Right now, tanks destroy stored fluids. This needs to be fixed. It's a massive violation of resource conversation, and unfairly destroys a lot of resources.

Right now, accidentally dropping sand into a fluid destroys stored fluids. It's a massive violation of resource conversation, and unfairly destroys a lot of resources. It's a bit of a stretch, I agree, but fluids are - objectively! - easier to destroy than other blocks in block form, as they can be displaced.

>Someone at some point will try to mine a tank to move it

That's fairly easy to solve: give the tank a very high hardness if it contains liquid in it, thus acting as a reminder that perhaps there's another way to mine it. Minecraft uses the exact same logic for indicating that an incorrect tool is being used, which ALSO results in the block being mined being irreversibly destroyed (try mining iron ore with a bare hand!).

>how the player's fluid carrying capacity with full tanks would be nothing compared to block carrying capacity

Minecraft does not use cubic meters as a unit. The player can carry 36 stacks of items, whereas a chest can store 27; the player can carry 36 buckets, whereas a tank can store 16. When discussing large-scale transport, as you seem to be focusing on, we should not be looking at cubic meters (which do not matter in Minecraft for this), but at actual carrying capacity by the items the game provides.

>Not everyone wants to have to build some sort of pipe/rail system to transport fluids from one place to another

You already have to do this for large quantities of items. There are mods which solve this for both items and fluids (such as wireless item/liquid transfer mods, or mods which add both portable item and liquid containers). This is not a category we're interested in. Charset's goal was never to cater to every player.

The walking back and forth is tedious, grindy, and menial, but vanilla more or less forces you to do it anyway! If solutions are to be found, they should be considered in the context of both items and liquids.

In addition, I still see no common purpose for large-scale transfer of *either*. The two usecases I could find are "transporting mined resources" (which, in my ultimate vision, usually means you found a large-scale mine or reservoir of some kind and will need significant amounts of time to fully harness its contents, necessiating setting up a more permanent transport network) or "moving bases" (which has no reason not to be logistically challenging, as not having it be so effectively makes it less rational to ever settle anywhere). In addition, one of the most common usecases for large-scale fluid usage in the first place is (a) lava-based power - which already required you to carry large amounts of buckets there in the first place! - and (b) TCon metals, which should be automatically convertible into the more convienent form of ingots and blocks. I guess Forestry may be a practical usecase worth looking into in this regard and seeing if it would benefit from this.

>A config option

No.

"WHY DID THIS TANK LOSE MY FLUID"

"Charset by default loses fluid conte---"

"IT DIDN'T DO IT IN THE PREVIOUS PACK I PLAYED"

"Yes, that's because the modpack deve---"

"I DON'T CARE IT SAID CHARSET"

"Yes, because you could conf---"

"YOU ARE A TERRIBLE MOD AUTHOR GIVE ME MY 16 BUCKETS OF IMPOSSIBLIUM BACK"

I welcome people to fork the mod for balance changes, renaming the mod appropriately as to avoid user confusion, but config options will not be added for things as key as this.

>How users want to use the mod's tanks should be up to them, anyway.

Then other users will get a false impression of my mod and inevitably complain when every other modpack has tanks - which are named the same and look the same - act differently.

**Comment by copygirl** [comment] 2018-02-28 17:46
I would welcome config options for both options **1** and **4**. They could even be both turned on at the same time. Explosions could cause the tank to blow up, while players breaking them would keep them intact - with contents!

About 1 being dangerous: That's kind of the point. Heck, it might even be used some weird, useful way. Of course this still leaves open the task of making it clear to players what is going to happen when they break the tank without emptying it.

A possible solution could be: Make them break speed slower (and uneffective by mining speed boosts), show liquid particles and make the noises the liquid would make, perhaps spawn finite sheets of the liquid, which could disappear quickly (or not), on top or around the block as you get close to breaking it (could use up part of the contents).

(**edit:** Repeating some of what asie said because I was typing my comment at the same time.)

----

On the no to config options: I don't agree. I use lots of balance and usability config options in Wearable Backpacks. I see many people asking and noting about not being able to wear chestplate armor at the same time. I don't mind pushing some responsibility to modpack creators and, when users complain to you, redirect them to their modpack creator / server owner.

**Comment by asiekierka** [comment] 2018-02-28 17:55
Yes, I already considered making them break slowly for #1. Your other ideas also make sense, and this will almost definitely be implemented.

I am aware my opinion on config options is a bit strict, however I am not likely to change it. Options in WearableBackpacks being enabled or disabled generally do not cause destructive side-effects - an option to preserve contents very well could. (However, configuring things such as barrel/tank storage capacity is something I am considering.)

In other words, we're getting #1, we're making it clearer for users that tanks will drop their contents in a very... literal sense, we're not doing #4 and leaving that to other mods instead.

As for #1 being usable in a weird, useful way: Factorization had a cool mechanic where - to craft Diamond Shards, a key crafting component - you had to blow up a Diamond Block with TNT. Indeed, these kinds of mechanics can not only add an element of danger to an otherwise (too?) peaceful game, they can also lead to interesting in-world interactions.

**Comment by alexbobp** [comment] 2018-02-28 22:16
This is reasonable as a feature request, but your point starts to look idiotic when you act like it's a design problem.  Plenty of mods offer plenty of storage solutions that aren't portable while full, and that's for reasonable balance reasons.  Perhaps you have a different expectation of balance, that's fine, that's why it's open source...

Objective problem: Right now, tanks destroy stored fluids. This needs to be fixed. It's a massive violation of resource conservation, and unfairly destroys a lot of resources.
Objective solution: player understands how mod works and doesn't break tanks while they're full; takes responsibility for own actions

**Comment by asiekierka** [comment] 2018-02-28 22:23
@alexbobp No, the player shouldn't expect the mod to be counter-intuitive - that part of the criticism is fair, so...

Objective solution: player does not know how mod works, but notices the tank is very hard to break when it contains fluid; player realizes vanilla does the same thing in regards to resource conservation violations (such as breaking a block of iron ore without the correct tool) and refrains from continuing.

This will be implemented in an upcoming update. Later updates will bring additional tweaks to tanks.

**Comment by alexbobp** [comment] 2018-03-01 00:11
The idea that it's counterintuitive is nonsense.  It resembles the vanilla cauldron which is a very old block.

That said, I support this improvement, which does make it *more* intuitive.

**Comment by ChloeDawn** [comment] 2018-03-01 03:40
I support this objective solution

**Comment by asiekierka** [comment] 2018-03-03 07:32
* Improved tank handling: [done](https://gfycat.com/LeadingMildGuillemot)
* Tank fluid spillage on break/explosion + very hard to break if has liquid: done
* Minor improvements here and there: done

And so, it is done.

**Closed as completed by asiekierka** 2018-03-03 07:32 UTC
