### ISSUE TITLE
game froze up after making audio tape

### ISSUE THREAD

**Issue by SDUBZ** [asiekierka/CharsetMC#49] opened 2016-01-27 04:41 UTC
made a audio tape and followed recipe but it made a 2 mintue tap not a 8 minute one and then went to record in tape drive and it made the game freeze up and didnt go back to responsive after so had to force close

**Comment by Toothwitch** [comment] 2016-01-27 18:12
This is no issue at all. If you push the record button a small file dialog without icons opens in the background(where you can select the music file) and until you close it minecraft will stay frozen.

**Comment by skyem123** [comment] 2016-01-28 10:03
Then maybe there should be a notice that the dialog box had opened?

**Comment by Toothwitch** [comment] 2016-01-28 12:55
That would at least be a way to tell people that it's not a bug.

**Comment by SDUBZ** [comment] 2016-01-28 13:48
tried it again today and it opened but last time i didnt see no dialog box
nothing it straight up froze up

**Comment by Toothwitch** [comment] 2016-01-28 14:45
yeah had that problem at first too but the window hides pretty well at the first time. after you used it once, it will always open in front of minecraft instead of somewhere behind it.

**Closed** 2016-03-06 10:52 UTC
Labels: bug
