### ISSUE TITLE
Unable to upload sound files since forge 14.23.5.2851

### ISSUE THREAD

**Issue by InvalidArgument3** [asiekierka/CharsetMC#450] opened 2020-09-15 10:31 UTC
When using a version of forge past 14.23.5.2847, The record player is unable to upload files, and this error displays in the console.

> [05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: paulscode/sound/codecs/CodecIBXM
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getCodec(AudioRecordThread.java:80)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.addIfCodec(AudioRecordThread.java:46)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getSupportedExtensionList(AudioRecordThread.java:54)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.AudioRecordThread.getSupportedExtensions(AudioRecordThread.java:41)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at pl.asie.charset.module.audio.storage.GuiRecordPlayer$DialogThread.run(GuiRecordPlayer.java:48)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: paulscode.sound.codecs.CodecIBXM
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[05:25:14] [Thread-14/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by asiekierka** [comment] 2020-09-27 08:55
Duplicate of https://github.com/CharsetMC/Charset/issues/444

**Closed as completed by asiekierka** 2020-09-27 08:55 UTC
Labels: duplicate
